import { test, expect } from '@playwright/test'
import { injectTelegramWebApp } from './helpers/telegram'

test('dashboard floating menu opens, dismisses, and opens themes', async ({ page }) => {
  await injectTelegramWebApp(page)
  await page.route('**/api/coins/tasks', (route) => route.fulfill({ json: { ok: true, tasks: [] } }))
  await page.route('**/api/boss/state', (route) => route.fulfill({ status: 503, json: { error: 'Unavailable in menu fixture' } }))
  await page.goto('/app.html#/')
  const trigger = page.getByRole('button', { name: 'Menyu', exact: true })
  await expect(trigger).toBeVisible()
  await page.screenshot({ path: `test-results/dashboard-fab-${test.info().project.name}.png` })
  const subjectPicker = page.getByRole('button', { name: /Fan tanlash:/ })
  await expect(subjectPicker).toHaveCount(1)
  await expect(page.locator('#home-learning-subject')).toHaveCount(0)
  await subjectPicker.click()
  await expect(page.getByRole('dialog').last()).toBeVisible()
  await expect(trigger).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeVisible()
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Menyu', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Temalar' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Yutuqlar' })).toBeVisible()
  await page.screenshot({ path: `test-results/dashboard-menu-${test.info().project.name}.png` })
  await page.mouse.click(10, 100)
  await expect(dialog).toBeHidden()
  await trigger.click()
  await page.getByRole('button', { name: 'Temalar' }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('dialog').last()).toBeVisible()
  await page.keyboard.press('Escape')
  await page.locator('.theme-toggle-btn').click()
  await page.waitForTimeout(600)
  await page.screenshot({ path: `test-results/dashboard-fab-light-${test.info().project.name}.png` })
})
