-- Email authentication + security features migration
-- Adds: email verification, password reset, device tracking, login history, audit logs

--> statement-breakpoint
-- 1) Update auth_identities constraint to include 'email' provider
ALTER TABLE "auth_identities" DROP CONSTRAINT "chk_auth_identities_provider";--> statement-breakpoint
ALTER TABLE "auth_identities" ADD CONSTRAINT "chk_auth_identities_provider"
  CHECK ("provider" IN ('telegram','phone','email','google','apple'));--> statement-breakpoint

-- 2) Update sessions constraint to include new providers
ALTER TABLE "sessions" DROP CONSTRAINT "chk_sessions_provider";--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "chk_sessions_provider"
  CHECK ("provider" IN ('telegram','phone','email','google','apple'));--> statement-breakpoint

-- 3) Email verification tokens (64-char random hex, single-use via DELETE...RETURNING)
-- Multiple active tokens per (user_id, email) allowed: user can request resend before previous expires
CREATE TABLE "email_verification_tokens" (
  "token" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "email" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "email_verification_tokens_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade,
  CONSTRAINT "chk_email_verification_token_len" CHECK (length("token") = 64),
  CONSTRAINT "chk_email_verification_expires" CHECK ("expires_at" > "created_at")
);--> statement-breakpoint
CREATE INDEX "idx_email_verification_user" ON "email_verification_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_email_verification_expires" ON "email_verification_tokens" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_email_verification_email" ON "email_verification_tokens" USING btree ("email");--> statement-breakpoint

-- 4) Password reset tokens (64-char random hex, consumed via used_at timestamp)
-- Multiple active tokens per user allowed: supports concurrent reset requests from different devices
CREATE TABLE "password_reset_tokens" (
  "token" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "password_reset_tokens_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade,
  CONSTRAINT "chk_password_reset_token_len" CHECK (length("token") = 64),
  CONSTRAINT "chk_password_reset_expires" CHECK ("expires_at" > "created_at")
);--> statement-breakpoint
CREATE INDEX "idx_password_reset_user" ON "password_reset_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_password_reset_expires" ON "password_reset_tokens" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_password_reset_unused" ON "password_reset_tokens" USING btree ("used_at") WHERE "used_at" IS NULL;--> statement-breakpoint

-- 5) Device tracking
-- Note: device_id generated by application (fingerprint hash) before insert
CREATE TABLE "user_devices" (
  "id" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "device_name" text,
  "device_type" text,
  "os" text,
  "browser" text,
  "ip_address" text,
  "user_agent" text,
  "fingerprint" text,
  "last_active_at" timestamp DEFAULT now() NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "user_devices_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade
);--> statement-breakpoint
CREATE INDEX "idx_user_devices_user" ON "user_devices" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_user_devices_last_active" ON "user_devices" USING btree ("last_active_at");--> statement-breakpoint
CREATE INDEX "idx_user_devices_fingerprint" ON "user_devices" USING btree ("fingerprint");--> statement-breakpoint

-- 6) Login history
CREATE TABLE "login_history" (
  "id" serial PRIMARY KEY,
  "user_id" text NOT NULL,
  "provider" text NOT NULL,
  "device_id" text,
  "ip_address" text,
  "user_agent" text,
  "success" boolean NOT NULL,
  "failure_reason" text,
  "location" jsonb,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "login_history_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade,
  CONSTRAINT "login_history_device_id_user_devices_id_fk"
    FOREIGN KEY ("device_id") REFERENCES "public"."user_devices"("id") ON DELETE set null ON UPDATE cascade
);--> statement-breakpoint
CREATE INDEX "idx_login_history_user_created" ON "login_history" USING btree ("user_id", "created_at" DESC);--> statement-breakpoint
CREATE INDEX "idx_login_history_created" ON "login_history" USING btree ("created_at" DESC);--> statement-breakpoint

-- 7) Audit logs
CREATE TABLE "audit_logs" (
  "id" serial PRIMARY KEY,
  "user_id" text,
  "action" text NOT NULL,
  "resource_type" text,
  "resource_id" text,
  "changes" jsonb,
  "ip_address" text,
  "user_agent" text,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "audit_logs_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE cascade
);--> statement-breakpoint
CREATE INDEX "idx_audit_logs_user_created" ON "audit_logs" USING btree ("user_id", "created_at" DESC);--> statement-breakpoint
CREATE INDEX "idx_audit_logs_action_created" ON "audit_logs" USING btree ("action", "created_at" DESC);--> statement-breakpoint
CREATE INDEX "idx_audit_logs_resource" ON "audit_logs" USING btree ("resource_type", "resource_id");--> statement-breakpoint

-- 8) Account security tracking columns on users table
ALTER TABLE "users" ADD COLUMN "email" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "email_verified_at" timestamp;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "failed_login_attempts" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "locked_until" timestamp;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "last_login_at" timestamp;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "last_password_change_at" timestamp;--> statement-breakpoint

-- 9) Add unique constraint on email (case-insensitive) - drizzle-kit doesn't generate this
CREATE UNIQUE INDEX "idx_users_email_unique" ON "users" USING btree (LOWER("email")) WHERE "email" IS NOT NULL;--> statement-breakpoint

-- 10) Add CHECK constraint on failed login attempts
ALTER TABLE "users" ADD CONSTRAINT "chk_users_failed_attempts_nonnegative" CHECK ("failed_login_attempts" >= 0);--> statement-breakpoint

-- 11) Add session device tracking
ALTER TABLE "sessions" ADD COLUMN "device_id" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "ip_address" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "user_agent" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "remember_me" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_device_id_user_devices_id_fk"
  FOREIGN KEY ("device_id") REFERENCES "public"."user_devices"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
