import { sql } from 'drizzle-orm'
import {
  pgTable, pgEnum, serial, text,
  integer, boolean, jsonb, timestamp, unique, index, check, primaryKey, real,
} from 'drizzle-orm/pg-core'

export const tariffEnum   = pgEnum('tariff',     ['free', 'premium'])
export const fontSizeEnum = pgEnum('font_size',  ['small', 'medium', 'large'])
export const fontStyleEnum= pgEnum('font_style', ['default', 'serif', 'mono'])
export const languageEnum = pgEnum('language',   ['uz', 'ru'])
export const themeEnum    = pgEnum('theme',       ['dark', 'light', 'system'])

/** Liga tartibi — YAGONA MANBA. `progress.league` CHECK constraint ham shunga bog'langan. */
export const LEAGUE_ORDER = ['bronze', 'silver', 'gold', 'platinum'] as const
export type League = typeof LEAGUE_ORDER[number]

export const users = pgTable('users', {
  /** Canonical user id (text): Telegram userlar uchun Telegram id raqam-string
   *  ('12345...'), telefon+parol akkauntlari uchun 'p_<digits>' ('p_998901234567'),
   *  email akkauntlari uchun 'e_<uuid>' format.
   *  Provider akkaunt → user xaritasi `auth_identities` jadvalida (multi-provider auth). */
  id:        text('id').primaryKey(),
  firstName: text('first_name').notNull(),
  lastName:  text('last_name').default(''),
  username:  text('username').default(''),
  photoUrl:  text('photo_url').default(''),
  phone:     text('phone'),
  email:     text('email'),
  emailVerifiedAt: timestamp('email_verified_at'),
  /** SMS marketing CONSENT (opt-in) — telefon ulash ≠ rozilik; user O'ZI yoqadi.
   *  Audit uchun timestamp bilan (kim, qachon rozilik berdi). */
  smsOptIn:      boolean('sms_opt_in').default(false).notNull(),
  smsOptedInAt:  timestamp('sms_opted_in_at'),
  tariff:    tariffEnum('tariff').default('free').notNull(),
  /** Referal mukofoti: shu san'gacha premium (tariff='premium' umrbod ham bor) */
  premiumUntil: timestamp('premium_until'),
  /** Bepul trial bir marta berilgan vaqt — premiumUntil'dan alohida idempotency flag. */
  trialGrantedAt: timestamp('trial_granted_at'),
  /** Admin panel ruxsati (savol CRUD). Faqat qo'lda DB orqali beriladi. */
  isAdmin:    boolean('is_admin').default(false).notNull(),
  /** Joriy avatar ramkasi (do'kon buyumi, avatar-frames config id'si).
   *  NULL — ramkasiz. Egalik faqat user_items orqali tekshiriladi (equip guard). */
  avatarFrame: text('avatar_frame'),
  /** Qo'lda yuklangan avatar — siqilgan 256px WebP (eski WebView'da JPEG fallback)
   *  data URL (base64, ~10-20KB).
   *  photo_url'dan ALOHIDA: photo_url har init'da Telegram initData bilan ustiga
   *  yoziladi; custom avatar SHU YERDA — global ko'rsatish uchun YAGONA manba
   *  (leaderboard/duel GET /api/users/:id/avatar orqali). NULL — custom avatar yo'q. */
  avatarWebp: text('avatar_webp'),
  /** Security tracking */
  failedLoginAttempts: integer('failed_login_attempts').default(0).notNull(),
  lockedUntil: timestamp('locked_until'),
  lastLoginAt: timestamp('last_login_at'),
  lastPasswordChangeAt: timestamp('last_password_change_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  // Note: Unique constraint created in migration (unique partial index not supported by Drizzle)
  check('chk_users_failed_attempts_nonnegative', sql`${t.failedLoginAttempts} >= 0`),
  index('idx_users_phone').on(t.phone),
])

/**
 * Auth identity'lar — canonical user (users.id) ↔ provider akkaunt xaritasi
 * (multi-provider auth). PK (provider, provider_uid): bitta Telegram akkaunt /
 * telefon raqam / email faqat BITTA user'ga tegishli bo'ladi.
 * `password_hash` provider='phone' va provider='email' uchun (scrypt "salt:hash" hex).
 * OAuth provider'lar (google, apple) parolsiz.
 * Linking: bitta user'ga bir necha identity (masalan telegram + phone + email) ulansa
 * bo'ladi — barcha qatorlar bir xil user_id'ga ishora qiladi.
 */
export const authIdentities = pgTable('auth_identities', {
  provider:     text('provider').notNull(),
  providerUid:  text('provider_uid').notNull(),
  userId:       text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  passwordHash: text('password_hash'),
  createdAt:    timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  primaryKey({ columns: [t.provider, t.providerUid] }),
  index('idx_auth_identities_user').on(t.userId),
  check('chk_auth_identities_provider', sql`${t.provider} IN ('telegram','phone','email','google','apple')`),
])

/**
 * User devices — fingerprint-based device tracking for security and multi-device sessions.
 * Device id generated by application (hash of user agent + IP + other signals).
 * Fields nullable because device info may not always be available (legacy sessions, proxies).
 */
export const userDevices = pgTable('user_devices', {
  id:           text('id').primaryKey(),
  userId:       text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  deviceName:   text('device_name'),
  deviceType:   text('device_type'),
  os:           text('os'),
  browser:      text('browser'),
  ipAddress:    text('ip_address'),
  userAgent:    text('user_agent'),
  fingerprint:  text('fingerprint'),
  lastActiveAt: timestamp('last_active_at').defaultNow().notNull(),
  createdAt:    timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_user_devices_user').on(t.userId),
  index('idx_user_devices_last_active').on(t.lastActiveAt),
  index('idx_user_devices_fingerprint').on(t.fingerprint),
])

/**
 * Login sessiyalari — opaque token (64-hex) JWT EMAS, DB'da esa FAQAT
 * sha256 hash'i saqlanadi (M10; xom token faqat client'da + Telegram deep-link
 * oqimining ≤5 daqiqalik tranzit kodida). Hashlash auth.repository'da.
 * `Authorization: Bearer <token>` middleware/auth.ts orqali resolve qilinadi;
 * revoke = qatorni DELETE qilish. expires_at o'tgan sessiyalar bekor.
 * Multi-provider support: telegram, phone, email, google, apple.
 */
export const sessions = pgTable('sessions', {
  token:     text('token').primaryKey(),
  userId:    text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** Sessiya qaysi provider login'i orqali yaratilgan */
  provider:  text('provider').notNull(),
  deviceId:  text('device_id').references(() => userDevices.id, { onDelete: 'set null', onUpdate: 'cascade' }),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  rememberMe: boolean('remember_me').default(false).notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_sessions_user').on(t.userId),
  index('idx_sessions_expires').on(t.expiresAt),
  index('idx_sessions_device').on(t.deviceId),
  check('chk_sessions_provider', sql`${t.provider} IN ('telegram','phone','email','google','apple')`),
])

/**
 * Email verification tokens — single-use tokens for email confirmation.
 * Multiple active tokens per (user_id, email) allowed for resend support.
 */
export const emailVerificationTokens = pgTable('email_verification_tokens', {
  token:     text('token').primaryKey(),
  userId:    text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  email:     text('email').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_email_verification_user_email').on(t.userId, t.email),
  index('idx_email_verification_expires').on(t.expiresAt),
  check('chk_email_verification_token_len', sql`length(${t.token}) = 64`),
  check('chk_email_verification_expires', sql`${t.expiresAt} > ${t.createdAt}`),
])

/**
 * Password reset tokens — consumed via used_at timestamp (not deleted on use).
 * Multiple active tokens per user allowed for concurrent reset from different devices.
 */
export const passwordResetTokens = pgTable('password_reset_tokens', {
  token:     text('token').primaryKey(),
  userId:    text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  expiresAt: timestamp('expires_at').notNull(),
  usedAt:    timestamp('used_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  // Composite for checking expiry per user
  index('idx_password_reset_user_expires').on(t.userId, t.expiresAt),
  // Partial index for unused tokens (validation query pattern)
  index('idx_password_reset_unused').on(t.userId).where(sql`${t.usedAt} IS NULL`),
  // Cleanup cron index
  index('idx_password_reset_expires').on(t.expiresAt),
  check('chk_password_reset_token_len', sql`length(${t.token}) = 64`),
  check('chk_password_reset_expires', sql`${t.expiresAt} > ${t.createdAt}`),
])

/**
 * Login history — audit trail of all login attempts (successful and failed).
 * Retention policy managed by cron (e.g., keep last 90 days).
 */
export const loginHistory = pgTable('login_history', {
  id:            serial('id').primaryKey(),
  userId:        text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  provider:      text('provider').notNull(),
  deviceId:      text('device_id').references(() => userDevices.id, { onDelete: 'set null', onUpdate: 'cascade' }),
  ipAddress:     text('ip_address'),
  userAgent:     text('user_agent'),
  success:       boolean('success').notNull(),
  failureReason: text('failure_reason'),
  location:      jsonb('location').$type<{ country?: string; city?: string; }>(),
  createdAt:     timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_login_history_user_created').on(t.userId, t.createdAt.desc()),
  // Cleanup cron: DELETE WHERE createdAt < (now() - interval '90 days')
  index('idx_login_history_created').on(t.createdAt.desc()),
  check('chk_login_history_provider', sql`${t.provider} IN ('telegram','phone','email','google','apple')`),
])

/**
 * Audit logs — system-wide audit trail for sensitive operations.
 * Standard actions (non-exhaustive): account_created, account_deleted, password_changed,
 * email_verified, email_changed, account_linked, account_unlinked, permission_changed,
 * admin_action, suspicious_activity, account_locked, account_unlocked.
 * Action naming convention: lowercase_snake_case, minimum 3 characters.
 */
export const auditLogs = pgTable('audit_logs', {
  id:           serial('id').primaryKey(),
  userId:       text('user_id').references(() => users.id, { onDelete: 'set null', onUpdate: 'cascade' }),
  action:       text('action').notNull(),
  resourceType: text('resource_type'),
  resourceId:   text('resource_id'),
  changes:      jsonb('changes').$type<Record<string, unknown>>(),
  ipAddress:    text('ip_address'),
  userAgent:    text('user_agent'),
  createdAt:    timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_audit_logs_user_created').on(t.userId, t.createdAt.desc()),
  index('idx_audit_logs_action_created').on(t.action, t.createdAt.desc()),
  index('idx_audit_logs_resource').on(t.resourceType, t.resourceId),
  // Action validation: lowercase_snake_case, min 3 chars (extensible, not exhaustive enum)
  check('chk_audit_logs_action_format', sql`${t.action} ~ '^[a-z][a-z0-9_]{2,}$'`),
])

/**
 * Telegram ulash kodlari — telefon+parol sessiyali foydalanuvchi APK/brauzerdan
 * `t.me/<bot>?start=link_<code>` deep-link ochadi; bot kodni BIR MARTA ishlatib
 * (atomik DELETE...RETURNING) Telegram identity'sini shu user'ga ulaydi.
 */
export const linkCodes = pgTable('link_codes', {
  code:      text('code').primaryKey(),
  userId:    text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_link_codes_user').on(t.userId),
])

/**
 * SMS OTP kodlar — register/login SMS verification uchun.
 * Bitta telefon uchun faqat BITTA aktiv kod (yangi kod eskisini replace qiladi).
 * Kod 5 daqiqa amal qiladi, BIR MARTA ishlatiladi (atomik DELETE...RETURNING).
 * codeHash = HMAC-SHA256(OTP_PEPPER) yoki pepper'siz SHA-256 (plain text
 * DB'da saqlanmaydi, faqat SMS'da yuboriladi).
 * attempts — noto'g'ri verify urinishlari hisoblagichi (brute-force lockout:
 * 5 ta urinishdan keyin kod o'lik, yangi kod so'rash kerak).
 */
export const otpCodes = pgTable('otp_codes', {
  phone:     text('phone').primaryKey(),
  codeHash:  text('code_hash').notNull(),
  attempts:  integer('attempts').default(0).notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_otp_codes_expires').on(t.expiresAt),
])

/**
 * Telegram LOGIN kodlari (web):
 * Brauzerda "Telegram orqali kirish" → bot deep-link (`login_<code>`);
 * client `/auth/telegram-login/:code` ni poll qiladi. Bot contact oqimi
 * telefon orqali user'ni topib `session_token` yozadi; kod topilgach
 * iste'mol qilinadi (DELETE). `session_token` NULL = hali pending.
 * (DIQQAT: kod phone user emas, balki har qanday login sessiyasiga xizmat
 * qiladi — shu sababli users FK'siz, mustaqil jadval.)
 * `session_token` bu yerda XOM (client raw token olishi shart) — lekin
 * tranzit: 5 daqiqa TTL + single-use DELETE, sessions'dagidek 30 kun emas.
 */
export const telegramLoginCodes = pgTable('telegram_login_codes', {
  code:         text('code').primaryKey(),
  sessionToken: text('session_token'),
  // Pending-login holati (D1 — serverless multi-instance): in-memory Map'dan
  // DB'ga ko'chirildi. Bot'ning 3 bosqichi (/start login_, contact, tasdiqlash)
  // turli Vercel instancelarda yurganda ham bir xil holat ko'rinadi.
  tgUserId:   text('tg_user_id'),                             // pending egasi (TG user)
  tgPhone:    text('tg_phone'),                               // contact'dan keyin
  tgProfile:  jsonb('tg_profile').$type<Record<string, unknown>>(), // {id, first_name,...}
  expiresAt:    timestamp('expires_at').notNull(),
  createdAt:    timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_tg_login_codes_tg_user').on(t.tgUserId),
])

/**
 * Test javobi idempotency token'lari — offline outbox replay'da
 * (so'rov serverga yetib borgan, javob yo'qolgan) counterlar ikki marta
 * oshmasligi uchun. Client har mantiqiy javob uchun 1 token yaratadi;
 * replay XUDDI SHU token bilan keladi → ON CONFLICT DO NOTHING → duplicate.
 */
export const answerTokens = pgTable('answer_tokens', {
  token:     text('token').primaryKey(),
  userId:    text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_answer_tokens_created').on(t.createdAt),
])

/** Telegram Stars to'lovlari — charge ID ledger va idempotency manbai. */
export const payments = pgTable('payments', {
  id:                       serial('id').primaryKey(),
  telegramPaymentChargeId:  text('telegram_payment_charge_id').notNull().unique(),
  providerPaymentChargeId:  text('provider_payment_charge_id').notNull(),
  userId:                   text('user_id').notNull().references(() => users.id, { onDelete: 'restrict', onUpdate: 'cascade' }),
  plan:                     text('plan').notNull(),
  amount:                   integer('amount').notNull(),
  currency:                 text('currency').notNull(),
  payload:                  text('payload').notNull(),
  status:                   text('status').default('completed').notNull(),
  rawUpdate:                jsonb('raw_update').$type<Record<string, unknown>>().default({}).notNull(),
  createdAt:                timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_payments_user_created').on(t.userId, t.createdAt),
])

export const paymentOrders = pgTable('payment_orders', {
  id:              serial('id').primaryKey(),
  orderId:         text('order_id').notNull().unique(),
  userId:          text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  plan:            text('plan').notNull(), // 'month' | 'year' | 'lifetime'
  amountUzs:       integer('amount_uzs').notNull(),
  provider:        text('provider').notNull(), // 'click' | 'payme'
  status:          text('status').default('pending').notNull(), // 'pending' | 'completed' | 'cancelled' | 'failed'
  providerTransId: text('provider_trans_id'), // Click transaction ID
  rawDetails:      jsonb('raw_details').$type<Record<string, unknown>>().default({}).notNull(),
  createdAt:       timestamp('created_at').defaultNow().notNull(),
  updatedAt:       timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  index('idx_payment_orders_user').on(t.userId, t.createdAt),
  // orderId UNIQUE → uning o'z implicit index'i bor (duplikat idx o'chirildi, migration 0045)
])

export const progress = pgTable('progress', {
  id:            serial('id').primaryKey(),
  userId:        text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }).unique(),
  totalCorrect:  integer('total_correct').default(0).notNull(),
  totalWrong:    integer('total_wrong').default(0).notNull(),
  totalAnswered: integer('total_answered').default(0).notNull(),
  streak:        integer('streak').default(0).notNull(),
  wrongByTicket: jsonb('wrong_by_ticket').$type<Record<string, number>>().default({}).notNull(),
  // L-5 (audit 2026-08-31): deprecated ustunlar O'CHIRILDI (migration 0057):
  //  - solved_questions / correct_questions → `progress_questions` jadvali (P2 backfill 0043)
  //  - daily_streak / last_daily_date       → `daily_streaks` jadvali (fan bo'yicha)
  /** Oktagon (PvP) g'alabalar soni — WS server match yakunida yozadi (Yutuqlar) */
  octagonWins:  integer('octagon_wins').default(0).notNull(),
  /** Haftalik liga darajasi — cron har dushanba 30% otiradi/tushiradi */
  league:       text('league').default('bronze').notNull(),
  /** Umrbod XP — o'rganish HODISASIGA qarab beriladi (birinchi to'g'ri javob,
   *  xatoni tuzatish), `total_correct` bilan bir xil emas. Level shundan
   *  hisoblanadi (`shared/xp.ts`). Sarflanmaydi, nolga tushmaydi. */
  xp:           integer('xp').default(0).notNull(),
  updatedAt:     timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  // Leaderboard queries sort by totalCorrect
  index('idx_progress_total_correct').on(t.totalCorrect.desc()),
  // Data integrity: counterlar manfiy bo'la olmaydi va summa idempotent hisoblanishi shart
  check('chk_progress_nonnegative', sql`
    ${t.totalCorrect} >= 0 AND ${t.totalWrong} >= 0 AND ${t.totalAnswered} >= 0
    AND ${t.streak} >= 0 AND ${t.octagonWins} >= 0 AND ${t.xp} >= 0
  `),
  check('chk_progress_sum', sql`${t.totalAnswered} = ${t.totalCorrect} + ${t.totalWrong}`),
  // Registrydan tashqari liga qiymati yozilmasligi kerak (LEAGUE_ORDER bilan sinxron)
  check('chk_progress_league', sql`${t.league} IN ('bronze', 'silver', 'gold', 'platinum')`),
])

// P2 (audit): jsonb massivlar (solved/correct_questions) quadratic rewrite
// edi — har javobda BUTUN massiv qayta yozilardi. Normalizatsiya: har javob
// O(1) upsert; anti-farm gate index orqali EXISTS.
export const progressQuestions = pgTable('progress_questions', {
  userId:     text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  subjectId:  text('subject_id').notNull(),
  questionId: integer('question_id').notNull(),
  /** Qachonlardir TO'G'RI yechilganmi (anti-farm gate: replay to'g'ri javob ball yozmaydi). Bir marta true bo'lsa orqaga qaytmaydi. */
  correct:    boolean('correct').default(false).notNull(),
  answeredAt: timestamp('answered_at').defaultNow().notNull(),
  /** BIRINCHI urinishga ketgan vaqt (ms) — savol qiyinligini keyinchalik
   *  ma'lumotdan chiqarish uchun (qo'lda "oson/qiyin" belgilanmaydi).
   *  Faqat insert paytida yoziladi, keyingi urinishlar o'zgartirmaydi. */
  firstMs:    integer('first_ms'),
  /** OXIRGI urinishga ketgan vaqt (ms) — tezlik dinamikasi (bilib qoldimi?) */
  lastMs:     integer('last_ms'),
}, (t) => [
  primaryKey({ columns: [t.userId, t.subjectId, t.questionId] }),
  index('idx_progress_questions_user').on(t.userId, t.subjectId),
  // Aql bovar qilmaydigan qiymatlar yozilmasin (soat/kun emas — 10 daqiqa shift)
  check('chk_progress_questions_ms', sql`
    (${t.firstMs} IS NULL OR (${t.firstMs} >= 0 AND ${t.firstMs} <= 600000))
    AND (${t.lastMs} IS NULL OR (${t.lastMs} >= 0 AND ${t.lastMs} <= 600000))
  `),
])

/**
 * Kunlik shiftlar hisobi — bitta foydalanuvchi bir kunda qancha XP va coin
 * ISHLAB TOPGANI (`shared/xp.ts` dagi XP_DAILY_CAP / COINS_DAILY_ANSWER_CAP).
 *
 * Nega alohida jadval: shift FAN bo'yicha emas, FOYDALANUVCHI bo'yicha —
 * `daily_records` (user, date, subject) buni bera olmaydi. Yozuv `recordAnswer`
 * CTE'sining bir qismi, ya'ni javob bilan bitta atomik statementda.
 */
export const dailyLimits = pgTable('daily_limits', {
  userId:       text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** 'YYYY-MM-DD' — Asia/Tashkent (daily_records bilan bir xil manba) */
  date:         text('date').notNull(),
  /** Shu kuni berilgan XP (shiftgacha) */
  xpEarned:     integer('xp_earned').default(0).notNull(),
  /** Shu kuni JAVOBLARDAN olingan coin (vazifa/streak mukofotlari kirmaydi) */
  coinsEarned:  integer('coins_earned').default(0).notNull(),
  updatedAt:    timestamp('updated_at').defaultNow().notNull(),
}, (t) => [
  primaryKey({ columns: [t.userId, t.date] }),
  check('chk_daily_limits_nonnegative', sql`${t.xpEarned} >= 0 AND ${t.coinsEarned} >= 0`),
  check('chk_daily_limits_date_fmt', sql`${t.date} ~ '^\\d{4}-\\d{2}-\\d{2}$'`),
])

export const userSettings = pgTable('settings', {
  id:              serial('id').primaryKey(),
  userId:          text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }).unique(),
  autoNextCorrect: boolean('auto_next_correct').default(true).notNull(),
  autoNextWrong:   boolean('auto_next_wrong').default(false).notNull(),
  noAnimation:     boolean('no_animation').default(false).notNull(),
  shuffleOptions:  boolean('shuffle_options').default(false).notNull(),
  fontSize:        fontSizeEnum('font_size').default('medium').notNull(),
  fontStyle:       fontStyleEnum('font_style').default('default').notNull(),
  language:        languageEnum('language').default('uz').notNull(),
  theme:           themeEnum('theme').default('dark').notNull(),
  offlineMode:     boolean('offline_mode').default(false).notNull(),
})

/**
 * Savol bankalari — canonical question identity poydevori (multi-fan).
 *
 * Banka id = `shared/subjects.ts` dagi `dataSourceId` (provider id) — YAGONA
 * MANBA o'sha fayl; jadvalga qator yangi fan bazasi migratsiyasida qo'shiladi.
 * Savolning GLOBAL identifikatori: (bank_id, external_id) juftligi;
 * `questions.id` esa faqat qulay surrogate key (frontend/WS numeric id'da qoladi).
 */
export const questionBanks = pgTable('question_banks', {
  id:        text('id').primaryKey(),
  name:      text('name').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

export const topics = pgTable('topics', {
  id:     serial('id').primaryKey(),
  nameUz: text('name_uz').notNull(),
  nameRu: text('name_ru').notNull(),
  slug:   text('slug').notNull().unique(),
  /** Topic qaysi bankaga tegishli — turli bankalar topic'lari chalkashmasligi uchun */
  bankId: text('bank_id').default('traffic_rules_db').notNull()
    .references(() => questionBanks.id, { onDelete: 'restrict' }),
})

export const questions = pgTable('questions', {
  id:            integer('id').primaryKey(),
  /** Savol qaysi bankaga tegishli (provider/dataSource id) */
  bankId:        text('bank_id').default('traffic_rules_db').notNull()
    .references(() => questionBanks.id, { onDelete: 'restrict' }),
  /** Banka ICHIDAGI barqaror id — banka o'z raqamlash tizimiga ega bo'lishi mumkin.
   *  Canonical identity: (bank_id, external_id) — UNIQUE. YHQ'da id::text. */
  externalId:    text('external_id').notNull(),
  questionUz:    text('question_uz').notNull(),
  questionRu:    text('question_ru').notNull(),
  optionsUz:     jsonb('options_uz').$type<Record<string, string>>().notNull(),
  optionsRu:     jsonb('options_ru').$type<Record<string, string>>().notNull(),
  correctAnswer: text('correct_answer').notNull(),
  image:         text('image'),
  topicId:       integer('topic_id').references(() => topics.id),
}, (t) => [
  unique('uq_question_external').on(t.bankId, t.externalId),
  index('idx_questions_bank_topic').on(t.bankId, t.topicId),
])

/**
 * Savolga oid STATIK tushuntirishlar — free foydalanuvchilar uchun
 * (AI Tutor premium-only). Bo'sh bo'lsa endpoint darslik darsidan
 * derive qilingan fallback matn qaytaradi; admin keyin per-question
 * aniq tushuntirish yozishi mumkin.
 */
export const questionExplanations = pgTable('question_explanations', {
  questionId:    integer('question_id').primaryKey().references(() => questions.id, { onDelete: 'cascade' }),
  explanationUz: text('explanation_uz').notNull(),
  explanationRu: text('explanation_ru').notNull(),
  updatedAt:     timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
})

export const savedQuestions = pgTable('saved_questions', {
  id:         serial('id').primaryKey(),
  userId:     text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  questionId: integer('question_id').notNull().references(() => questions.id, { onDelete: 'cascade' }),
  /** Multi-fan identity: bir xil questionId turli fanlarda alohida bookmark.
   *  Eski qatorlar migratsiyada 'yhq' bilan to'ldirilgan (traffic_rules_db). */
  subjectId:  text('subject_id').default('yhq').notNull(),
}, (t) => [unique('uq_saved').on(t.userId, t.subjectId, t.questionId)])

/**
 * Spaced Repetition (SM-2) kartalari — moslashuvchan test rejimi (Adaptive).
 * Har bir foydalanuvchi va fan bo'yicha savol xotira parametrlari (EF, interval, reps, dueAt).
 */
export const cardProgress = pgTable('card_progress', {
  id:         serial('id').primaryKey(),
  userId:     text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  subjectId:  text('subject_id').default('yhq').notNull(),
  questionId: integer('question_id').notNull().references(() => questions.id, { onDelete: 'cascade' }),
  ef:         real('ef').default(2.5).notNull(),
  interval:   integer('interval').default(1).notNull(),
  reps:       integer('reps').default(0).notNull(),
  dueAt:      timestamp('due_at').notNull(),
  updatedAt:  timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  unique('uq_card_progress').on(t.userId, t.subjectId, t.questionId),
  index('idx_card_user_subject').on(t.userId, t.subjectId),
])

/** Referal qaydlari — referee faqat bir marta hisoblanadi (anti-farm). */
export const referrals = pgTable('referrals', {
  id:         serial('id').primaryKey(),
  referrerId: text('referrer_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  refereeId:  text('referee_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** pending = qayd etildi, mukofot referee ELIGIBILITY Answers yechmaguncha kutmoqda;
   *  rewarded = mukofot ikkala tomonga berildi (progress CTE atomik yozadi). */
  status:     text('status').$type<'pending' | 'rewarded'>().default('pending').notNull(),
  rewardedAt: timestamp('rewarded_at'),
  createdAt:  timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_referral_referee').on(t.refereeId),
  index('idx_referrals_referrer_status').on(t.referrerId, t.status),
])

/** KPI eventlar (1 haftalik sinov) — activation/retention/premium_click o'lchash */
export const analyticsEvents = pgTable('analytics_events', {  id:        serial('id').primaryKey(),
  userId:    text('user_id').references(() => users.id, { onDelete: 'set null', onUpdate: 'cascade' }),
  event:     text('event').notNull(),
  props:     jsonb('props').$type<Record<string, unknown>>().default({}).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_events_user_time').on(t.userId, t.createdAt),
  index('idx_events_name_time').on(t.event, t.createdAt),
])

/**
 * Kunlik topshiriq seriyasi — HAR BIR FAN UCHUN ALOHIDA.
 * (user_id, subject_id) juftligi bo'yicha bitta qator: o'sha fanning
 * ketma-ket bajarilgan kunlari soni va oxirgi bajarilgan sana.
 */
/** Cron period ledger — bir job bir davrda faqat bir marta bajariladi. */
export const jobRuns = pgTable('job_runs', {
  id:         serial('id').primaryKey(),
  jobName:    text('job_name').notNull(),
  periodKey:  text('period_key').notNull(),
  status:     text('status').default('running').notNull(),
  startedAt:  timestamp('started_at').defaultNow().notNull(),
  finishedAt: timestamp('finished_at'),
  details:    jsonb('details').$type<Record<string, unknown>>().default({}).notNull(),
}, (t) => [
  unique('uq_job_run_period').on(t.jobName, t.periodKey),
])

/**
 * DB-backed rate limit counter'lari — multi-instance (Vercel/Render replicalar)
 * uchun UMUMIY oyna (in-memory Map har instance'da alohida edi — hujumchi
 * replica soni × limit olardi). Fixed 60s oyna: bucket = '<limiter>:<route>:<ip>'.
 * Eskirgan qatorlar kunlik cron tozalashi bilan o'chadi (window_start < 1 soat).
 */
export const rateLimits = pgTable('rate_limits', {
  bucket:      text('bucket').primaryKey(),
  count:       integer('count').notNull(),
  windowStart: timestamp('window_start').notNull(),
  createdAt:   timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_rate_limits_window').on(t.windowStart),
])

/**
 * League rollover REJASI jurnali — cron rollover'ni retry-safe qiladi.
 * Reja (user → from/to liga) avval BITTA atomik INSERT bilan shu yerga yoziladi;
 * UPDATE'lar `progress.league = from_league` guard bilan bajariladi. Crash'dan
 * keyingi qayta ishga tushirish rejalashtirishni SKIP qiladi (jurnal o'sha
 * davrning aniq rejasini saqlaydi) — qayta-promote/demote bo'lmaydi.
 * Xato bo'lsa jobRuns 'running' qoladi → stale-lease (1 soat) qayta urinishga
 * ruxsat beradi; muvaffaqiyatda 'completed' (qayta o'ynamaydi).
 */
export const leagueRolloverLog = pgTable('league_rollover_log', {
  id:         serial('id').primaryKey(),
  userId:     text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** Hafta boshi ('YYYY-MM-DD') — jobRuns.periodKey bilan bir xil */
  periodKey:  text('period_key').notNull(),
  fromLeague: text('from_league').notNull(),
  toLeague:   text('to_league').notNull(),
  createdAt:  timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_rollover_user_period').on(t.userId, t.periodKey),
  index('idx_rollover_period').on(t.periodKey),
])

/**
 * AI Tutor kunlik foydalanish kvotasi — Gemini API cost control.
 * user_id = '0' qatori GLOBAL kunlik byudjetni bildiradi (FK yo'q — shu
 * sababli references ham yo'q); qolgan qatorlar haqiqiy user kvotasi.
 */
export const tutorUsage = pgTable('tutor_usage', {
  userId: text('user_id').notNull(),
  /** 'YYYY-MM-DD' — Asia/Tashkent (tashkentDate utili bilan bir xil) */
  date:   text('date').notNull(),
  count:  integer('count').default(0).notNull(),
}, (t) => [
  unique('uq_tutor_usage').on(t.userId, t.date),
  check('chk_tutor_usage_nonnegative', sql`${t.count} >= 0`),
  check('chk_tutor_usage_date_fmt', sql`${t.date} ~ '^\\d{4}-\\d{2}-\\d{2}$'`),
])

export const dailyStreaks = pgTable('daily_streaks', {
  id:            serial('id').primaryKey(),
  userId:        text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  subjectId:     text('subject_id').notNull(),
  /** Shu fan bo'yicha ketma-ket bajarilgan kunlar soni */
  streak:        integer('streak').default(0).notNull(),
  /** Shu fan bo'yicha oxirgi kunlik topshiriq sanasi — 'YYYY-MM-DD' (client local) */
  lastDailyDate: text('last_daily_date'),
  updatedAt:     timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  unique('uq_daily_streak').on(t.userId, t.subjectId),
  check('chk_daily_streak_nonnegative', sql`${t.streak} >= 0`),
  check('chk_daily_streak_date_fmt', sql`${t.lastDailyDate} IS NULL OR ${t.lastDailyDate} ~ '^\\d{4}-\\d{2}-\\d{2}$'`),
])

/**
 * Kunlik topshiriq yozuvlari — har kun + fan uchun bitta qator.
 * dailyStreak hisoblash `daily_streaks` jadvalida (lastDailyDate asosida),
 * bu jadval esa tarix/kunlik statistika uchun.
 */
export const dailyRecords = pgTable('daily_records', {
  id:          serial('id').primaryKey(),
  userId:      text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** 'YYYY-MM-DD' — client local sanasi (Telegram user o'z vaqt zonasi) */
  date:        text('date').notNull(),
  subjectId:   text('subject_id').notNull(),
  answered:    integer('answered').default(0).notNull(),
  correct:     integer('correct').default(0).notNull(),
  /** Shu kunda tuzatilgan eski xatolar soni (Intizom sahifasidagi "TUZATILDI") */
  fixed:       integer('fixed').default(0).notNull(),
  /** Kunlik 5 talik topshiriq yakunlandimi (Dashboard'dagi "Tayyor" belgisi) */
  challengeDone: boolean('challenge_done').default(false).notNull(),
  completedAt: timestamp('completed_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_daily_record').on(t.userId, t.date, t.subjectId),
  index('idx_daily_user_date').on(t.userId, t.date),
  // Leaderboard weeklyTop: date >= weekStart filtri + user_id bo'yicha agregatsiya
  index('idx_daily_date').on(t.date),
  // Data integrity: answered/correct/fixed manfiy bo'lmasligi va correct answered'dan
  // oshmasligi shart (bug yoki xato requestdan shubhali statistika paydo bo'lmasin).
  check('chk_daily_record_nonnegative', sql`${t.answered} >= 0 AND ${t.fixed} >= 0`),
  check('chk_daily_record_correct_le', sql`${t.correct} BETWEEN 0 AND ${t.answered}`),
  check('chk_daily_record_date_fmt', sql`${t.date} ~ '^\\d{4}-\\d{2}-\\d{2}$'`),
])

/**
 * Promokodlar — avtomaktablar, aksiyalar va hamkorlar uchun.
 * type='premium_days' (masalan value=30 -> 30 kunlik Premium).
 */
export const promoCodes = pgTable('promo_codes', {
  id: serial('id').primaryKey(),
  code: text('code').notNull(),
  type: text('type').notNull().default('premium_days'),
  value: integer('value').notNull(),
  maxUses: integer('max_uses'),
  usedCount: integer('used_count').default(0).notNull(),
  expiresAt: timestamp('expires_at'),
  isActive: boolean('is_active').default(true).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_promo_code').on(t.code),
  check('chk_promo_value_positive', sql`${t.value} > 0`),
  check('chk_promo_used_count_nonnegative', sql`${t.usedCount} >= 0`),
])

/**
 * Promokod ishlatilganlik yozuvlari — 1 kishi 1 marta ishlatishi uchun.
 */
export const promoCodeRedemptions = pgTable('promo_code_redemptions', {
  id: serial('id').primaryKey(),
  promoCodeId: integer('promo_code_id').notNull().references(() => promoCodes.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  redeemedAt: timestamp('redeemed_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_promo_redemption').on(t.promoCodeId, t.userId),
  index('idx_promo_redemptions_user').on(t.userId),
])

/**
 * Haftalik turnir g'oliblari va mukofotlari — har dushanba cron orqali avtomatik taqsimlanadi.
 */
export const tournamentPrizes = pgTable('tournament_prizes', {
  id:         serial('id').primaryKey(),
  periodKey:  text('period_key').notNull(), // masalan '2026-08-10' (o'tgan hafta dushanbasi)
  userId:     text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  rank:       integer('rank').notNull(), // 1, 2, 3
  score:      integer('score').default(0).notNull(),
  league:     text('league').default('bronze').notNull(),
  prizeDays:  integer('prize_days').notNull(), // 30, 14, 7
  createdAt:  timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_tournament_prize_period_rank').on(t.periodKey, t.rank),
  index('idx_tournament_prizes_user').on(t.userId),
  index('idx_tournament_prizes_period').on(t.periodKey),
])




/**
 * SMS marketing kampaniyalari — FAQAT sms_opt_in=TRUE userlarga
 * (verified telefonlar, Eskiz.uz orqali). Chunk'li dispatch: har
 * /admin/sms/campaigns/:id/send chaqiruvi bitta batch yuboradi
 * (Vercel serverless timeout'ga mos) — admin UI remaining=0 bo'lguncha
 * davom ettiradi.
 */
export const smsCampaigns = pgTable('sms_campaigns', {
  id:           serial('id').primaryKey(),
  title:        text('title').notNull(),
  message:      text('message').notNull(),
  /** draft → sending (recipientlar yaratilgan, chunk'lar ketmoqda) → sent */
  status:       text('status').$type<'draft' | 'sending' | 'sent'>().default('draft').notNull(),
  targetCount:  integer('target_count').default(0).notNull(),
  sentCount:    integer('sent_count').default(0).notNull(),
  failedCount:  integer('failed_count').default(0).notNull(),
  createdAt:    timestamp('created_at').defaultNow().notNull(),
  finishedAt:   timestamp('finished_at'),
})

/** Kampaniya qabul qiluvchilari — audience snapshot (birinchi dispatch'da
 *  freeze qilinadi: keyin opt-out qilganlar ham shu kampaniyaga tushmaydi,
 *  histoya uchun saqlanadi). Phone snapshot — user keyin raqam almasatsa ham. */
export const smsCampaignRecipients = pgTable('sms_campaign_recipients', {
  id:         serial('id').primaryKey(),
  campaignId: integer('campaign_id').notNull().references(() => smsCampaigns.id, { onDelete: 'cascade' }),
  /** FK yo'q: user o'chirilsa ham yetkazib berish tarixi saqlanadi */
  userId:     text('user_id').notNull(),
  phone:      text('phone').notNull(),
  status:     text('status').$type<'pending' | 'sending' | 'sent' | 'failed'>().default('pending').notNull(),
  /** Claim qilingan vaqt — crash'da 'sending'da QOTGAN qatorlarni stale-reclaim
   *  qilish uchun (M-4 residual): claimed_at < now()-10min qayta pending hisoblanadi */
  claimedAt:  timestamp('claimed_at'),
  error:      text('error'),
  sentAt:     timestamp('sent_at'),
  createdAt:  timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_sms_recipients_campaign').on(t.campaignId, t.status),
])

// ── Telegram BROADCAST kampaniyalari (M-5: chunked, resumable — broadcast.service
//    eski full-table-load + 30s truncation muammosini yopadi) ────────────────
export const tgBroadcasts = pgTable('tg_broadcasts', {
  id:         serial('id').primaryKey(),
  segment:    text('segment').notNull().$type<'all' | 'free' | 'premium' | 'inactive_7d' | 'active_today'>(),
  message:    text('message').notNull(),
  imageUrl:   text('image_url'),
  buttonText: text('button_text'),
  buttonUrl:  text('button_url'),
  /** Telegram file_id keshi — birinchi muvaffaqiyatli yuborishdan keyin rasm URL o'rniga ishlatiladi */
  photoFileId: text('photo_file_id'),
  status:     text('status').$type<'draft' | 'sending' | 'sent'>().default('draft').notNull(),
  targetCount:  integer('target_count').default(0).notNull(),
  sentCount:    integer('sent_count').default(0).notNull(),
  blockedCount: integer('blocked_count').default(0).notNull(),
  failedCount:  integer('failed_count').default(0).notNull(),
  createdAt:  timestamp('created_at').defaultNow().notNull(),
  finishedAt: timestamp('finished_at'),
})

export const tgBroadcastRecipients = pgTable('tg_broadcast_recipients', {
  id:          serial('id').primaryKey(),
  broadcastId: integer('broadcast_id').notNull().references(() => tgBroadcasts.id, { onDelete: 'cascade' }),
  /** Telegram numeric chat id — string (JS number precision chegarasidan xavfsiz) */
  tgId:        text('tg_id').notNull(),
  status:      text('status').$type<'pending' | 'sending' | 'sent' | 'blocked' | 'failed'>().default('pending').notNull(),
  /** Crash'da 'sending'da qotganlarni stale-reclaim qilish uchun (sms-campaign kabi) */
  claimedAt:   timestamp('claimed_at'),
  error:       text('error'),
  sentAt:      timestamp('sent_at'),
  createdAt:   timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  index('idx_tg_recipients_broadcast').on(t.broadcastId, t.status),
])

// ── COINS IQTISODIYOTI (FIXPLAN #40) ─────────────────────────────────────────
// Uch jadval: balans (hot-path), tranzaksiyalar ledger (audit + idempotency),
// egalik (durable buyumlar). Tanga FAQAT server'da mint/debit qilinadi —
// client hech qachon o'z balansini yozmaydi (scoring trust boundary kabi).

/**
 * Coin balansi — user boshiga 1 qator (faqat coin'i bo'lgan userlar).
 * Qator yo'q = balans 0 (LEFT JOIN semantikasi; init'da yaratilmaydi —
 * birinchi mint/purchase'da lazily upsert qilinadi).
 */
export const userCoins = pgTable('user_coins', {
  userId:    text('user_id').primaryKey().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  balance:   integer('balance').default(0).notNull(),
  updatedAt: timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  check('chk_user_coins_nonnegative', sql`${t.balance} >= 0`),
])

/**
 * Coin tranzaksiyalari ledger — har bir mint/debit/refund qaydi.
 * `UNIQUE(user_id, reason, ref_id)` — idempotency: bir mantiqiy amal
 * (javob clientToken'i, xarid purchaseId'si, task claim kuni, merch order id)
 * hech qachon ikki marta yozilmaydi. Audit: kim, nima uchun, qachon.
 * reason'lar: 'answer' | 'purchase' | 'task_claim' | 'merch' | 'merch_refund' | 'admin'
 */
export const coinTransactions = pgTable('coin_transactions', {
  id:        serial('id').primaryKey(),
  userId:    text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** + mint/refund, − debit (purchase/merch) */
  delta:     integer('delta').notNull(),
  reason:    text('reason').notNull(),
  /** Idempotency kaliti: javob clientToken | purchaseId | 'taskId:YYYY-MM-DD' | order id */
  refId:     text('ref_id').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_coin_tx_ref').on(t.userId, t.reason, t.refId),
  index('idx_coin_tx_user_time').on(t.userId, t.createdAt),
  check('chk_coin_tx_delta_nonzero', sql`${t.delta} <> 0`),
])

/**
 * Egalik (durable buyumlar) — tema/ramka bitta marta sotib olinadi va
 * umrbod qoladi. Consumable (premium_days) BU YERGA YOZILMAYDI.
 * item_id = shared/shop-items.ts katalog id'si (tema id YOKI 'frame-*' id).
 */
export const userItems = pgTable('user_items', {
  userId:     text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  itemId:     text('item_id').notNull(),
  acquiredAt: timestamp('acquired_at').defaultNow().notNull(),
}, (t) => [
  primaryKey({ columns: [t.userId, t.itemId] }),
])

/**
 * Lucky Spin — kunlik 1 aylantirish (Lucky Spin feature).
 * PK user_id + atomik claim (`ON CONFLICT ... WHERE spin_date < yangi`) =
 * 1/kun strukturaviy (parallel so'rovlar serialize bo'ladi).
 * reward_id — shared/lucky-spin.ts segment id (audit; coin yutuqlar qo'shimcha
 * coin_transactions'da reason='spin' bilan yoziladi).
 * NOTE: coin_transactions.chk_delta_nonzero sababli premium yutuq bu yerda
 * audit qilinadi (delta=0 ledger'ga kira olmaydi).
 */
export const dailySpins = pgTable('daily_spins', {
  userId:    text('user_id').primaryKey().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** Tashkent kalendari 'YYYY-MM-DD' (daily_records kabi) */
  spinDate:  text('spin_date').notNull(),
  /** shared/lucky-spin segment id ('c5' | 'c100' | 'p1' ...) */
  rewardId:  text('reward_id').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

// ─── BOSS BATTLE (haftalik jamoaviy jang) ────────────────────────────────────

/**
 * Haftalik boss — period bo'yicha 1 qator (periodKey = Tashkent dushanbasi).
 * status: 'active' | 'defeated' (HP 0) | 'escaped' (vaqt o'tdi).
 * rewardsDistributed — rollover idempotency bayrog'i (ledger UNIQUE bilan birga).
 */
export const bossBattles = pgTable('boss_battles', {
  id:           serial('id').primaryKey(),
  /** Tashkent hafta boshi 'YYYY-MM-DD' (shared/boss-battle.bossPeriodKey) */
  periodKey:    text('period_key').notNull(),
  /** shared/boss-battle BOSS_ROSTER id */
  bossId:       text('boss_id').notNull(),
  hpTotal:      integer('hp_total').notNull(),
  hpLeft:       integer('hp_left').notNull(),
  /** 'active' | 'defeated' | 'escaped' */
  status:       text('status').notNull().default('active'),
  rewardsDistributed: boolean('rewards_distributed').notNull().default(false),
  createdAt:    timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  unique('uq_boss_period').on(t.periodKey),
])

/** Har userning shu boss'ga bergan umumiy zarari (mukofot asosiy) */
export const bossDamage = pgTable('boss_damage', {
  bossId:  integer('boss_id').notNull().references(() => bossBattles.id, { onDelete: 'cascade' }),
  userId:  text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  damage:  integer('damage').notNull().default(0),
  updatedAt: timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  primaryKey({ columns: [t.bossId, t.userId] }),
  check('chk_boss_damage_nonnegative', sql`${t.damage} >= 0`),
])

/**
 * MERCH buyurtmalari (FIXPLAN #40 Faza 3) — real fizik tovarlar coin'ga.
 * User boshiga har item'dan 1 TA faol buyurtma (CANCELLed tarix bo'lishi mumkin) —
 * bu limit purchase CTE'da `merch_orders` subquery'si bilan tekshiriladi.
 * `price_paid` — sotib olingan DAMqdagi narx snapshot'i (katalog narxi keyin
 * o'zgarsa ham refund to'g'ri hisoblanadi).
 * Status oqimi: new → contacted → delivered | cancelled (cancel = atomik refund).
 */
export const merchOrders = pgTable('merch_orders', {
  id:        serial('id').primaryKey(),
  userId:    text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  itemId:    text('item_id').notNull(),
  fullName:  text('full_name').notNull(),
  phone:     text('phone').notNull(),
  note:      text('note'),
  /** Coin'dagi narx snapshot'i (refund uchun authoritative) */
  pricePaid: integer('price_paid').notNull(),
  status:    text('status').$type<'new' | 'contacted' | 'delivered' | 'cancelled'>().default('new').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().$onUpdateFn(() => new Date()).notNull(),
}, (t) => [
  index('idx_merch_orders_user').on(t.userId),
  index('idx_merch_orders_status').on(t.status),
  index('idx_merch_orders_item').on(t.itemId),
  check('chk_merch_orders_price_positive', sql`${t.pricePaid} > 0`),
  // NOTE: partial UNIQUE index (user_id, item_id) WHERE status <> 'cancelled'
  // — drizzle partial index'ni qo'llamaydi (users.email kabi), qo'lda 0048
  // migratsiyasida (`uq_merch_active_user_item`). Claim-first anti-race: parallel
  // buyurtmalarda debit faqat claim g'olibiga (double-charge imkonsiz).
])

/**
 * Duel (Oktagon) natijalari — har match uchun HAR ISHTIROKCHIGA bitta qator
 * (bitta match = 2 qator; mehmon o'yinchi (`'0'`) uchun qator yozilmaydi).
 *
 * `progress.octagon_wins` umrbod hisoblagich bo'lib qoladi (yutuqlar + online
 * ro'yxat), bu jadval esa davr bo'yicha reyting uchun: leaderboard `duelTop`
 * kunlik/haftalik/oylik g'alaba-mag'lub-durangni shundan agregatlaydi.
 */
export const duelResults = pgTable('duel_results', {
  id:         serial('id').primaryKey(),
  matchId:    text('match_id').notNull(),
  userId:     text('user_id').notNull().references(() => users.id, { onDelete: 'cascade', onUpdate: 'cascade' }),
  /** Raqib id'si; raqib mehmon bo'lsa null */
  opponentId: text('opponent_id'),
  result:     text('result').$type<'win' | 'lose' | 'draw'>().notNull(),
  selfScore:  integer('self_score').default(0).notNull(),
  oppScore:   integer('opp_score').default(0).notNull(),
  /** Raqib diskonekt qilib taslim bo'ldimi (forfeit bilan yakunlangan match) */
  forfeit:    boolean('forfeit').default(false).notNull(),
  createdAt:  timestamp('created_at').defaultNow().notNull(),
}, (t) => [
  // endMatch/forfeit ikkalasi ham ishga tushsa ham natija ikki marta yozilmaydi
  unique('uq_duel_result_match_user').on(t.matchId, t.userId),
  // duelTop davr filtri: created_at >= davr boshi + user_id bo'yicha agregatsiya
  index('idx_duel_result_created').on(t.createdAt),
  index('idx_duel_result_user_created').on(t.userId, t.createdAt),
  check('chk_duel_result_kind', sql`${t.result} IN ('win','lose','draw')`),
  check('chk_duel_result_scores', sql`${t.selfScore} >= 0 AND ${t.oppScore} >= 0`),
])
